// ============================================================================
//  FakeBots :: BotMovement.h
//  Straight-line waypoint steering for on-foot bots and driven vehicles,
//  plus the follow-AI steering helper (used directly for FakeBotFollow and
//  indirectly for group formations). This is intentionally simple and
//  deterministic (no external pathfinding dependency) so it behaves the
//  same on every platform; gamemodes that need obstacle-aware routing can
//  feed dense waypoint queues generated by their own navmesh/graph and
//  FakeBots will follow them faithfully.
// ============================================================================
#pragma once

#include "Bot.h"

namespace FakeBots
{
    namespace BotMovement
    {
        // Advances an on-foot player straight-line toward (tx,ty,tz),
        // updating cached position, facing and (only on change) animation.
        // Returns true once within snapping distance. Exposed for reuse by
        // follow/combat-chase/idle-wander AI, none of which want the
        // waypoint-queue/"reached destination" callback side effects that
        // StepOnFoot() applies on top of this.
        bool StepTowardPoint(Bot &bot, int playerId, float tx, float ty, float tz, float speed, BotMoveType type, float deltaSeconds);

        // Advances on-foot movement by `deltaSeconds`, applies position,
        // facing angle and walk/run/sprint animation (only re-issuing the
        // animation native when the style actually changes), fires
        // OnFakeBotReachDestination / OnFakeBotWaypointReached as needed.
        void StepOnFoot(Bot &bot, float deltaSeconds);

        // Advances vehicle movement by `deltaSeconds` for a bot currently
        // driving (bot must be the driver of GetVehicleId()). Also drains
        // the drive-waypoint queue the same way StepOnFoot drains the
        // on-foot one.
        void StepDriving(Bot &bot, float deltaSeconds);

        // Continuously steers an on-foot bot toward `FollowTargetId`'s
        // current position plus its local (offsetX, offsetY) - used by
        // FakeBotFollow() and FakeBotGroupFollow().
        void StepFollow(Bot &bot, float deltaSeconds);
    }
}
