#!/usr/bin/env python3
"""
Generates third_party/raknet/SampCryptData.inc - the protocol constants a client needs
to be accepted by a SA-MP / open.mp server.

    python3 tools/gen_crypt_tables.py --raknet <openmultiplayer/RakNet checkout> \
                                      --samp-binary <samp03svr> \
                                      [--out third_party/raknet/SampCryptData.inc]

Sources
  * the datagram substitution key (kSampDecryptKey)  - open.mp RakNet fork, SAMPRakNet.cpp.
    It must be a bijection: the client needs its inverse.
  * the open.mp ID_AUTH_KEY table (kOmpAuthTable)     - same file, 256 {challenge,response}.
  * the SA-MP  ID_AUTH_KEY table (kSampAuthTable)     - read out of a real samp03svr binary:
    256 records of 96 bytes ({char challenge[32]; char response[64];}). The table is
    identical in 0.3.7-R2 and 0.3.DL-R1, i.e. it does not change between releases.

A real SA-MP server challenges with an entry of ITS table, an open.mp server with an entry of
its own table; the two tables share no entry, so the client carries both.
"""
import argparse
import pathlib
import re
import sys


def parse_openmp(path):
    src = pathlib.Path(path).read_text(encoding="utf-8", errors="replace")
    m = re.search(r"key\[256\]\s*=\s*\{(.*?)\};", src, re.S)
    key = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(1))]
    if len(key) != 256 or sorted(key) != list(range(256)):
        raise SystemExit("substitution key is not a 256 byte bijection")
    m = re.search(r"AuthTable\[UCHAR_MAX \+ 1\]\s*=\s*\{(.*?)\n\};", src, re.S)
    pairs = re.findall(r'\{\s*"([0-9A-Fa-f]+)"\s*,\s*"([0-9A-Fa-f]+)"\s*\}', m.group(1))
    if len(pairs) != 256:
        raise SystemExit(f"open.mp auth table: expected 256 pairs, found {len(pairs)}")
    return key, [(c.upper(), r.upper()) for c, r in pairs]


def parse_samp_binary(path):
    b = pathlib.Path(path).read_bytes()
    toks = [(m.start(), m.group().decode())
            for m in re.finditer(rb"(?<![0-9A-Za-z])[0-9A-F]{12,16}(?=\x00)|(?<![0-9A-Za-z])[0-9A-F]{40}(?=\x00)", b)]
    kind = lambda t: "R" if len(t[1]) == 40 else "C"
    best, cur = [], []
    for t in toks:
        if cur and kind(cur[-1]) == kind(t):
            best = cur if len(cur) > len(best) else best
            cur = []
        cur.append(t)
    best = cur if len(cur) > len(best) else best
    run = best
    while run and kind(run[0]) != "C":
        run = run[1:]
    if run and kind(run[-1]) != "R":
        run = run[:-1]
    pairs = [(run[i][1], run[i + 1][1]) for i in range(0, len(run) - 1, 2)]
    strides = {run[i + 2][0] - run[i][0] for i in range(0, len(run) - 2, 2)}
    if len(pairs) != 256 or strides != {96}:
        raise SystemExit(f"SA-MP auth table not found in {path} (pairs={len(pairs)}, strides={strides})")
    if len({c for c, _ in pairs}) != 256:
        raise SystemExit("SA-MP auth table has duplicate challenges")
    return pairs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--raknet", required=True, help="checkout of openmultiplayer/RakNet")
    ap.add_argument("--samp-binary", required=True, help="a samp03svr (Linux) binary")
    ap.add_argument("--out", default=str(pathlib.Path(__file__).resolve().parent.parent / "third_party/raknet/SampCryptData.inc"))
    a = ap.parse_args()

    key, omp = parse_openmp(pathlib.Path(a.raknet) / "SAMPRakNet.cpp")
    samp = parse_samp_binary(a.samp_binary)
    if {c for c, _ in samp} & {c for c, _ in omp}:
        print("note: the two tables share challenges (unexpected, harmless)", file=sys.stderr)

    out = [
        "// GENERATED by tools/gen_crypt_tables.py - do not edit.",
        "//   kSampDecryptKey : substitution table the server uses to decode client datagrams (a bijection)",
        "//   kSampAuthTable  : ID_AUTH_KEY {challenge, response} pairs of a SA-MP 0.3.7 / 0.3.DL server",
        "//   kOmpAuthTable   : ID_AUTH_KEY {challenge, response} pairs of an open.mp server",
        "static const unsigned char kSampDecryptKey[256] = {",
    ]
    for i in range(0, 256, 16):
        out.append("    " + ", ".join("0x%02X" % v for v in key[i:i + 16]) + ",")
    out += ["};", "struct SampAuthEntry { const char* challenge; const char* response; };"]
    for name, table in (("kSampAuthTable", samp), ("kOmpAuthTable", omp)):
        out.append(f"static const SampAuthEntry {name}[256] = {{")
        out += ['    { "%s", "%s" },' % (c, r) for c, r in table]
        out.append("};")
    pathlib.Path(a.out).write_text("\n".join(out) + "\n")
    print(f"wrote {a.out}: key bijection OK, {len(samp)} SA-MP pairs, {len(omp)} open.mp pairs")


if __name__ == "__main__":
    main()
