#!/usr/bin/env python3
"""Builds docs/TEST-REPORT.md from tests/results/*.json (written by tests/run_server_test.py)."""
import glob
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "tests" / "results"
ORDER = ["basic", "join", "overfill", "badname", "facing", "churn", "demo", "sample"]
NAMES = {"omp": "open.mp 1.5.8.3079 (Linux x86)", "samp": "SA-MP 0.3.7-R2 (Linux x86)"}


def load():
    rows = []
    for f in glob.glob(str(RES / "*.json")):
        d = json.load(open(f))
        d["file"] = pathlib.Path(f).name
        rows.append(d)
    return rows


def main():
    rows = load()
    if not rows:
        sys.exit("no results found in tests/results")
    out = []
    out.append("# Test report - FakeBots 3.2.0\n")
    out.append("Generated by `tools/make_test_report.py` from `tests/results/*.json`. Every row is a **real server** "
               "(started from scratch for that row) with the plugin loaded and the bots joining over the network; "
               "both servers run with **zero NPC slots**.\n")
    total_ok = sum(1 for r in rows if r.get("ok"))
    out.append(f"**{total_ok} of {len(rows)} runs passed.**\n")

    for kind in ("omp", "samp"):
        kr = [r for r in rows if r["kind"] == kind]
        if not kr:
            continue
        kr.sort(key=lambda r: (ORDER.index(r["scenario"]) if r["scenario"] in ORDER else 99, r.get("bots", 0)))
        out.append(f"## {NAMES[kind]}\n")
        out.append("| scenario | bots | slots | server browser count | all bots spawned in | in-game checks (pass/fail) | threads | RSS MB | CPU (% of one core) | clean shutdown | result |")
        out.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | :---: | :---: |")
        for r in kr:
            q = r.get("query_players", "-")
            checks = f"{r.get('passed', '-')}/{r.get('failed', '-')}"
            thr = r.get("threads", "-")
            rss = r.get("rss_mb", "-")
            cpu = r.get("server_cpu_percent", "-")
            if r["scenario"] == "churn" and r.get("rounds"):
                good = [x for x in r["rounds"] if x.get("threads") is not None and x.get("rss_mb") is not None]
                if good:
                    thr = f"{good[0]['threads']} -> {good[-1]['threads']} (1st -> last round)"
                    rss = f"{good[0]['rss_mb']} -> {good[-1]['rss_mb']}"
            if r["scenario"] in ("demo", "sample"):
                checks = "self-checking"
            spawned = "-"
            logf = RES / r["file"].replace(".json", ".log")
            if logf.exists():
                m = re.search(r"all (\d+) bots spawned in (\d+) ms", logf.read_text(errors="replace"))
                if m:
                    spawned = f"{int(m.group(2)) / 1000:.1f} s"
            out.append(f"| {r['scenario']} | {r.get('bots', '')} | {r.get('slots', '')} | {q} | {spawned} | {checks} | {thr} | {rss} | {cpu} | "
                       f"{'yes' if r.get('clean_shutdown') else 'NO'} | {'PASS' if r.get('ok') else '**FAIL**'} |")
        out.append("")

    out.append("## How to read it\n")
    out.append("* *server browser count* is what the public SA-MP query protocol reports from outside the server "
               "process (`players` of the `i` query); it must equal the number of bots.\n"
               "* *in-game checks* are the `PASS`/`FAIL` lines of the test gamemode (`tests/gamemode/`).\n"
               "* threads / RSS / CPU are those of the server process in the steady state with all bots connected "
               "(each bot owns one RakNet thread that wakes every 20 ms).\n"
               "* the `overfill` row additionally joins a *real outside player* (a different address) on the last "
               "free slot and requires that the server did not ban the bots' address.\n"
               "* raw logs: `tests/results/<server>-<scenario>-<bots>.log`.\n")
    out.append("## Reproduce\n\n```bash\n./run_all_tests.sh\n```\n\nSee [Testing.md](Testing.md).\n")
    (ROOT / "docs" / "TEST-REPORT.md").write_text("\n".join(out))
    print(f"wrote docs/TEST-REPORT.md ({len(rows)} runs, {total_ok} passed)")


if __name__ == "__main__":
    main()
